### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by xiaozhah** [kmisiunas/PlotCalendar#2]
`PlotCalendar[TimeSeries[{{DateObject[{2016, 1, 11}, TimeObject[{19, 57, 12.`}, TimeZone -> 8.`], TimeZone -> 8.`],1}, {DateObject[{2016, 1, 20}, TimeObject[{11, 15, 46.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}, {DateObject[{2016, 1, 28}, TimeObject[{22, 37, 23.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}{DateObject[{2016, 2, 8},  TimeObject[{17, 50, 1.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}, {DateObject[{2016, 2, 14},  TimeObject[{22, 53, 21.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}, {DateObject[{2016, 2, 18},TimeObject[{15, 42, 37.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}, {DateObject[{2016, 2, 20}, TimeObject[{21, 20, 11.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}, {DateObject[{2016, 2, 29}, TimeObject[{1, 10, 43.`}, TimeZone -> 8.`], TimeZone -> 8.`],  1}, {DateObject[{2016, 3, 3}, TimeObject[{17, 40, 42.`}, TimeZone -> 8.`], TimeZone -> 8.`], 1}, {DateObject[{2016, 3, 25}, TimeObject[{0, 25, 14.`}, TimeZone -> 8.`], TimeZone -> 8.`],  1}, {DateObject[{2016, 3, 30}, TimeObject[{19, 25, 23.`}, TimeZone -> 8.`], TimeZone -> 8.`], 2}}], "Years" -> 2016, ColorFunction -> "Rainbow"]`

gives error.But delete any element of this list get the right result.

![qq 20170201153231](https://cloud.githubusercontent.com/assets/7589403/22498493/b7f34578-e893-11e6-879c-d1f21c943e56.png)

**Comment by kmisiunas** [comment]
Did you figure out what was wrong?
